### ISSUE TITLE
Add Solution of below Problem

### ISSUE THREAD

**Issue by SumanSudhir** [SumanSudhir/LeetCode#4]
#Todo
- [ ] [0005.Longest Palindromic Substring](https://leetcode.com/problems/longest-palindromic-substring/)
- [ ] [0008.String to Integer (atoi)](https://leetcode.com/problems/string-to-integer-atoi)
- [ ] [0017.Letter Combinations of a Phone Number](https://leetcode.com/problems/letter-combinations-of-a-phone-number)
- [ ] [0022.Generate Parenthesis](https://leetcode.com/problems/generate-parentheses)
- [ ] [0023.Merge K Sorted List](https://leetcode.com/problems/merge-k-sorted-lists)
- [ ] [0025.Reverse Nodes in k-Group](https://leetcode.com/problems/reverse-nodes-in-k-group)
- [ ] [0030.Substring with Concatenation of All Words    ](https://leetcode.com/problems/substring-with-concatenation-of-all-words)
